# Generated by Django 4.2.6 on 2023-10-29 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulyar',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formulyar',
            name='books',
            field=models.TextField(verbose_name='O`quvchi olgan kitoblar'),
        ),
        migrations.AlterField(
            model_name='formulyar',
            name='last_name',
            field=models.CharField(max_length=500, verbose_name='O`quvchi Familiyasi'),
        ),
        migrations.AlterField(
            model_name='formulyar',
            name='name',
            field=models.CharField(max_length=500, verbose_name='O`quvchi ismi'),
        ),
        migrations.AlterField(
            model_name='formulyar',
            name='sinf',
            field=models.CharField(max_length=500, verbose_name='O`quvchi sinfi'),
        ),
    ]
